version: '3'
services:
    hic_app:
        build: .
        ports: 
            - 8000:8000
        volumes: 
            - .:/app
        restart: unless-stopped
        networks: 
            - postgres_dev
networks: 
    postgres_dev:
        external: 
            name: postgres_dev